# Generated by Django 5.1.7 on 2025-04-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technoss', '0002_game_novedades'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='oferta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
